

BASE_URL = 'http://nls.dev.cleveroad.com/api'
BASE_HEADERS = {'content-type': 'application/json'}
SUCCESS_STATUS_CODE = 200
BAD_REQUEST_STATUS_CODE = 400
EXISTING_ELEMENT_ERROR_STATUS_CODE = 422
UNAUTHORIZED_STATUS_CODE = 401
NOT_FOUND_STATUS_CODE = 404

